### ISSUE TITLE
multiple components w/o prop drilling

### ISSUE THREAD

**Issue by VinSpee** [tjdavies/hyper-redux#1]
Hi! I'm loving the way this looks and feels.

Any thoughts on having multiple components (nested) which rely on a piece of global state? Passing props down the chain is painful.

**Comment by faceyspacey** [comment]
Yea, how does it work for child components? Is this just the top level that receives state? How do you connect child components? And if you can, what about their props?

**Comment by tjdavies** [comment]
Hey sorry been busy! Glad you like this.  So currently only the top level receives state and you have to pass it down. This was a deliberate choice as it echos HyperApp (and by extension Elm). However as people who use redux are used to using connect i'm not overly against including it. I guess if its there that way you can take it of leave it as you like. I'll try and include it when i have some time!

**Comment by tjdavies** [comment]
@VinSpee @faceyspacey ok so i did it using the new context API. So you can access it anywhere like this.

`function ContextButton(): JSX.Element {
  return (
    <AppContext>
      {context => (
        <button onClick={() => context.actions.incrementDelayed(1)}>
          + delayed
        </button>
      )}
    </AppContext>
  );
}`

updated the demo to include an example. This is all nicely typed.

https://codesandbox.io/s/745pqpnoz6

**Comment by VinSpee** [comment]
beautiful. thanks!
